# Generated by Django 6.0.2 on 2026-02-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HasarTahmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rayic_bedel", models.FloatField()),
                ("hasar_bedeli", models.FloatField()),
                ("degisen_parca_sayisi", models.IntegerField()),
                ("onarilan_parca_sayisi", models.IntegerField()),
                ("arac_kilometresi", models.FloatField()),
                ("arac_yasi", models.IntegerField()),
                ("marka", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("arac_turu", models.CharField(blank=True, max_length=100, null=True)),
                ("arac_kodu", models.CharField(blank=True, max_length=50, null=True)),
                ("degisen_parcalar", models.JSONField(blank=True, null=True)),
                ("onarilan_parcalar", models.JSONField(blank=True, null=True)),
                ("parca_katsayilari", models.JSONField(blank=True, null=True)),
                ("tahmini", models.FloatField(blank=True, null=True)),
                ("min_deger", models.FloatField(blank=True, null=True)),
                ("max_deger", models.FloatField(blank=True, null=True)),
                ("uyari", models.TextField(blank=True, null=True)),
                ("katsayi_H_hasar", models.FloatField(blank=True, null=True)),
                ("knn_baseline", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
