# Generated by Django 5.0.6 on 2026-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontendUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="hasartahmin",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
