# Generated by Django 5.0.6 on 2026-02-17 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasar", "0002_frontenduser_alter_hasartahmin_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hasartahmin",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hasar_tahminleri",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
