# Generated by Django 5.0.6 on 2026-02-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasar", "0003_hasartahmin_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hasartahmin",
            name="frontend_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tahminler",
                to="hasar.frontenduser",
            ),
        ),
    ]
